### ISSUE TITLE
Twitch streams not loading as of around 3:30 pm CEST

### ISSUE THREAD

**Issue by RedSnt** [TTV-LOL/extensions#23]
With TTV LOL on the streams refuse to load, but disabling TTV LOL allows the stream to work just fine. I assume "they" just updated something.

**Comment by dancalderon** [comment]
Can confirm, I tried in different computers and it happened the same, seems like they introduced a fix to avoid the extension

**Comment by Neo-TA** [comment]
the api doesnt seem to be working on the website it connects to error:522

**Comment by GaryLlama** [comment]
I'm getting Error:2000

**Comment by Sqwrly** [comment]
I just get a spinning loading thing on FF.

**Comment by rlnt** [comment]
Yep, this is patched

**Comment by blunttheking** [comment]
Can confirm somethings up, long loading on live streams until finally an ad plays

**Comment by mangkoran** [comment]
8:48 MYT, finally streams load fine. I do experienced issues around that time too, but now I can normally watch streams again.

**Comment by Mrgglock** [comment]
Looks patched.

**Comment by JosiahWhite** [comment]
This has been corrected

**Comment by radlerandi** [comment]
loading error is back since one hour. Stream loads when ttv-lol is disabled.
